(()=>{'use strict';
const status=(m)=>{document.getElementById('status').textContent=m;};
const showOrder=(a)=>{document.getElementById('orderList').textContent=a.join('\n');};
const canvas=document.getElementById('gl');const gl=canvas.getContext('webgl');const vid=document.getElementById('vid');const drop=document.getElementById('drop');
if(!gl){status('WebGL not available.');throw new Error('WebGL');}
const isSecure=location.protocol==='https:'||location.hostname==='localhost';document.getElementById('banner').textContent=isSecure?'Secure origin: webcam allowed.':'Not secure origin → Webcam blocked (use HTTPS or localhost).';
const clickSfx=document.getElementById('clickSfx');clickSfx.src="data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACAAABAAEA/////wD///8AAP//AAD//wAA//8AAP///w==";
document.querySelectorAll('.sfx').forEach(b=>b.addEventListener('click',()=>{try{clickSfx.currentTime=0;clickSfx.play();}catch{}}));
const $=(id)=>document.getElementById(id);
const ui={cell:$('cell')||{value:24},str:$('strength')||{value:40},rgb:$('rgb')||{value:35},grain:$('grain')||{value:12},speed:$('speed')||{value:50}};
let order=['orient','warp','pixel','rgb','trail','ascii'];showOrder(order);
function sh(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(x));return x;}
function prog(v,f){const p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}
const VS=sh(gl.VERTEX_SHADER,'attribute vec2 aPos;attribute vec2 aUV;varying vec2 vUV;void main(){vUV=aUV;gl_Position=vec4(aPos,0.,1.);}');
const COM='precision mediump float;varying vec2 vUV;uniform sampler2D uTex;uniform vec2 uRes;uniform float uTime;';
const fsCopy=sh(gl.FRAGMENT_SHADER,COM+'void main(){gl_FragColor=texture2D(uTex,vUV);}');
const fsOrient=sh(gl.FRAGMENT_SHADER,COM+'uniform int uMode;vec2 map(vec2 uv){if(uMode==1)return vec2(1.0-uv.x,uv.y);if(uMode==2)return vec2(uv.x,1.0-uv.y);if(uMode==3)return vec2(1.0-uv.x,1.0-uv.y);return uv;}void main(){gl_FragColor=texture2D(uTex,map(vUV));}');
const fsWarp=sh(gl.FRAGMENT_SHADER,COM+'uniform float uStr,uRGB,uSpeed;vec2 d(float t){return vec2(cos(t*.7),sin(t*.9));}void main(){float t=uTime*uSpeed;vec2 uv=vUV;float w1=sin(uv.y*12.+1.2*t),w2=cos(uv.x*9.-1.1*t),w3=sin((uv.x+uv.y)*6.-.7*t);uv+=vec2(w1*w2,w3)*(uStr*.035);vec2 c=vec2(.5),q=uv-c;float r=length(q);float a=atan(q.y,q.x)+r*(uStr*.35)*sin(t*.4);uv=c+vec2(cos(a),sin(a))*r;vec2 off=d(t)*(uRGB*.004);gl_FragColor=vec4(texture2D(uTex,uv+off).r,texture2D(uTex,uv).g,texture2D(uTex,uv-off).b,1.);}');
const fsPixel=sh(gl.FRAGMENT_SHADER,COM+'uniform float uCell,uRGB;void main(){vec2 grid=uRes/max(uCell,1.);vec2 uvq=floor(vUV*grid)/grid;vec2 off=vec2(0.707)*(uRGB*0.004);gl_FragColor=vec4(texture2D(uTex,uvq+off).r,texture2D(uTex,uvq).g,texture2D(uTex,uvq-off).b,1.);}');
const fsRGB=sh(gl.FRAGMENT_SHADER,COM+'uniform float uAmt;void main(){vec2 off=vec2(cos(uTime*.7),sin(uTime*.9))*(uAmt*.004);gl_FragColor=vec4(texture2D(uTex,vUV+off).r,texture2D(uTex,vUV).g,texture2D(uTex,vUV-off).b,1.);}');
const fsHUDtxt=sh(gl.FRAGMENT_SHADER,COM+'uniform sampler2D uHUD;uniform float uAmt;void main(){vec4 base=texture2D(uTex,vUV);vec4 hud=texture2D(uHUD,vUV);gl_FragColor=vec4(mix(base.rgb,hud.rgb,hud.a*uAmt),1.);}');
const fsTrailU=sh(gl.FRAGMENT_SHADER,COM+'uniform sampler2D uCur;uniform sampler2D uTrail;uniform float uDecay;void main(){vec3 cur=texture2D(uCur,vUV).rgb;vec3 old=texture2D(uTrail,vUV).rgb;vec3 acc=mix(cur,old,clamp(uDecay,0.0,1.0));gl_FragColor=vec4(acc,1.);}');
const fsTrailM=sh(gl.FRAGMENT_SHADER,COM+'uniform sampler2D uCur;uniform sampler2D uTrail;uniform float uAmt;void main(){vec3 cur=texture2D(uCur,vUV).rgb;vec3 acc=texture2D(uTrail,vUV).rgb;gl_FragColor=vec4(mix(cur,acc,clamp(uAmt,0.0,1.0)),1.);}');
const P={copy:prog(VS,fsCopy),orient:prog(VS,fsOrient),warp:prog(VS,fsWarp),pixel:prog(VS,fsPixel),rgb:prog(VS,fsRGB),hudtxt:prog(VS,fsHUDtxt),trailU:prog(VS,fsTrailU),trailM:prog(VS,fsTrailM)};
const quad=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,quad);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,0,0,1,-1,1,0,-1,1,0,1,-1,1,1,0,1,1]),gl.STATIC_DRAW);
function use(p){gl.useProgram(p);const aPos=gl.getAttribLocation(p,'aPos');const aUV=gl.getAttribLocation(p,'aUV');gl.bindBuffer(gl.ARRAY_BUFFER,quad);
  gl.enableVertexAttribArray(aPos);gl.enableVertexAttribArray(aUV);gl.vertexAttribPointer(aPos,2,gl.FLOAT,false,16,0);gl.vertexAttribPointer(aUV,2,gl.FLOAT,false,16,8);
  const uRes=gl.getUniformLocation(p,'uRes');if(uRes)gl.uniform2f(uRes,canvas.width,canvas.height);const uTime=gl.getUniformLocation(p,'uTime');if(uTime)gl.uniform1f(uTime,performance.now()/1000);}
let fbA=null,fbB=null,texA=null,texB=null,srcTex=null;
function makeRT(w,h){function mkTex(){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);return t;}
  function mkFBO(t){const f=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,f);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,t,0);return f;}
  texA=mkTex();texB=mkTex();fbA=mkFBO(texA);fbB=mkFBO(texB);gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
function setCanvasSize(w,h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h);makeRT(w,h);allocTrail(w,h);asciiCanvas.width=w;asciiCanvas.height=h;gl.bindTexture(gl.TEXTURE_2D,asciiTex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);}
srcTex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,srcTex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
const trailTex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,trailTex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
const trailFB=gl.createFramebuffer();function allocTrail(w,h){gl.bindTexture(gl.TEXTURE_2D,trailTex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,trailFB);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,trailTex,0);gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
const asciiCanvas=document.createElement('canvas'),asciiCtx=asciiCanvas.getContext('2d');const asciiTex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,asciiTex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
const asciiChars=" .:-=+*#%@";function drawASCII(){const w=asciiCanvas.width,h=asciiCanvas.height;if(!w||!h)return;const size=12;const cols=Math.max(2,Math.floor(w/size));const rows=Math.max(2,Math.floor(h/size));const snap=document.createElement('canvas');const sctx=snap.getContext('2d');snap.width=cols;snap.height=rows;sctx.drawImage(canvas,0,0,cols,rows);const img=sctx.getImageData(0,0,cols,rows).data;asciiCtx.clearRect(0,0,w,h);asciiCtx.fillStyle='#000';asciiCtx.fillRect(0,0,w,h);asciiCtx.fillStyle='#0f0';asciiCtx.font='bold '+size+'px ui-monospace,Menlo,Consolas,monospace';asciiCtx.textBaseline='top';for(let y=0;y<rows;y++){for(let x=0;x<cols;x++){const idx=(y*cols+x)*4;const r=img[idx],g=img[idx+1],b=img[idx+2];const lum=0.2126*r+0.7152*g+0.0722*b;const p=lum/255;const ch=asciiChars[Math.floor(p*(asciiChars.length-1))];asciiCtx.fillText(ch,x*size,y*size);}}gl.activeTexture(gl.TEXTURE3);gl.bindTexture(gl.TEXTURE_2D,asciiTex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,asciiCanvas);gl.activeTexture(gl.TEXTURE0);}
function drawTo(texIn,fbOut,program,setu){gl.bindFramebuffer(gl.FRAMEBUFFER,fbOut);use(program);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texIn);const uTex=gl.getUniformLocation(program,'uTex');if(uTex)gl.uniform1i(uTex,0);if(setu)setu(program);gl.drawArrays(gl.TRIANGLES,0,6);gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
let currentOrientMode=0;
const steps={orient:(r,w)=>drawTo(r,w,P.orient,(p)=>{gl.uniform1i(gl.getUniformLocation(p,'uMode'),currentOrientMode);}),
  warp:(r,w)=>drawTo(r,w,P.warp,(p)=>{gl.uniform1f(gl.getUniformLocation(p,'uStr'),parseFloat(ui.str.value)/100);gl.uniform1f(gl.getUniformLocation(p,'uRGB'),parseFloat(ui.rgb.value)/100);gl.uniform1f(gl.getUniformLocation(p,'uSpeed'),parseFloat(ui.speed.value)/50);}),
  pixel:(r,w)=>drawTo(r,w,P.pixel,(p)=>{gl.uniform1f(gl.getUniformLocation(p,'uCell'),parseFloat(ui.cell.value));gl.uniform1f(gl.getUniformLocation(p,'uRGB'),parseFloat(ui.rgb.value)/100);}),
  rgb:(r,w)=>drawTo(r,w,P.rgb,(p)=>{gl.uniform1f(gl.getUniformLocation(p,'uAmt'),parseFloat(ui.rgb.value)/100);}),
  ascii:(r,w)=>{drawASCII();drawTo(r,w,P.hudtxt,(p)=>{gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,asciiTex);gl.uniform1i(gl.getUniformLocation(p,'uHUD'),1);gl.activeTexture(gl.TEXTURE0);gl.uniform1f(gl.getUniformLocation(p,'uAmt'),0.7);});},
};
const quad=gl.createBuffer(); // already created; kept for reference
function render(){requestAnimationFrame(render);
  if(vid.srcObject && !vid.paused && !vid.ended){gl.bindTexture(gl.TEXTURE_2D,srcTex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,vid);}
  let read=srcTex,writeFB=fbA,writeTex=texA;const swap=()=>{const tmp=writeTex;writeTex=(writeTex===texA?texB:texA);writeFB=(writeFB===fbA?fbB:fbA);read=tmp;};
  for(const name of order){steps[name](read,writeFB);swap();}
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);use(P.copy);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,read);gl.uniform1i(gl.getUniformLocation(P.copy,'uTex'),0);gl.drawArrays(gl.TRIANGLES,0,6);
}
render();
(function(){const ph=document.createElement('canvas');ph.width=800;ph.height=450;const ctx=ph.getContext('2d');const g=ctx.createLinearGradient(0,0,800,450);g.addColorStop(0,'#222');g.addColorStop(1,'#333');ctx.fillStyle=g;ctx.fillRect(0,0,800,450);setCanvasSize(ph.width,ph.height);gl.bindTexture(gl.TEXTURE_2D,srcTex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,ph);status('Ready. Upload an image or start webcam.');})();
function savePNG(){try{canvas.toBlob((b)=>{if(!b){alert('Could not export image.');return;}const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='distorted.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);},'image/png');}catch(e){console.error(e);alert('Download failed');}}
document.getElementById('btnSave').onclick=savePNG;
document.getElementById('btnUpload').onclick=()=>document.getElementById('file').click();
document.getElementById('btnShuffle').onclick=()=>{order=['orient','pixel','warp','rgb','ascii'];showOrder(order);};
document.getElementById('btnShuffle2').onclick=()=>{order=['orient','warp','rgb','pixel','ascii'];showOrder(order);};
document.getElementById('file').onchange=e=>{if(e.target.files[0]){const url=URL.createObjectURL(e.target.files[0]);const img=new Image();img.onload=()=>{URL.revokeObjectURL(url);setCanvasSize(img.width,img.height);gl.bindTexture(gl.TEXTURE_2D,srcTex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);status('Image loaded.');};img.src=url;}};
drop.ondragover=e=>{e.preventDefault();drop.style.background='#222';};drop.ondragleave=e=>{e.preventDefault();drop.style.background='';};
drop.ondrop=e=>{e.preventDefault();drop.style.background='';if(e.dataTransfer.files[0]){const url=URL.createObjectURL(e.dataTransfer.files[0]);const img=new Image();img.onload=()=>{URL.revokeObjectURL(url);setCanvasSize(img.width,img.height);gl.bindTexture(gl.TEXTURE_2D,srcTex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);status('Image loaded.');};img.src=url;}};
document.getElementById('btnCam').onclick=async()=>{if(!isSecure){alert('Webcam needs https or localhost');return;}try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});vid.srcObject=s;await new Promise(r=>{if(vid.readyState>=1&&vid.videoWidth)r();vid.onloadedmetadata=()=>r();});await vid.play();const w=vid.videoWidth||640,h=vid.videoHeight||480;setCanvasSize(w,h);drop.style.display='none';status('Webcam on');}catch(e){console.error(e);status('Webcam error: '+e.name);}};
})();